version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    hostname: zookeeper
    container_name: development_zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.9.0.1
    hostname: kafka
    container_name: development_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_CREATE_TOPICS: "lambda:1:1"
      
  cassandra:
    image: cassandra
    hostname: cassandra
    container_name: development_cassandra
    ports:
      - "9042:9042"

  postgres:
    image: postgres
    hostname: postgres
    container_name: development_postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword 
      POSTGRES_DB: lambda
    ports:
      - "5432:5432"
      
  zeppelin:
    image: apache/zeppelin:0.7.2
    hostname: zeppelin
    container_name: development_zeppelin
    ports: 
      - "8008:8080"
    links:
      - cassandra
    volumes:
      - ./zeppelin/interpreter.json:/zeppelin/conf/interpreter.json